### ISSUE TITLE
Access network specific items

### ISSUE THREAD

**Issue by yuanju-qwq** [AE2-UEL/NAE2#20]
1.Add a block so that the subnet can only access specific items and fluids from the main network to reduce the storage bus's occupation of tps
2.Can try mirroring or Block timing extracts a certain amount of items from the network to the set cache

**Comment by NotMyWing** [comment]
This should be covered in Storage Buses themselves when https://github.com/AE2-UEL/Applied-Energistics-2/pull/384 is merged. The initial scan would still read the entire network, but any upcoming changes will be done granularly.
