### ISSUE TITLE
Add calculation to AE2 pattern requesting

### ISSUE THREAD

**Issue by Niels1006** [AE2-UEL/NAE2#30]
Pretty useful to just order 16\*64\*5 or smth instead of using a calculator or a brain.

![image](https://github.com/NotMyWing/NAE2/assets/16525967/bd4271ba-1ebe-4d78-aa24-80ffd0378b65)

**Comment by NotMyWing** [comment]
I think this one is more fitting to be submitted in [PrototypeTrousers/Applied-Energistics-2](https://github.com/PrototypeTrousers/Applied-Energistics-2).

Though... given the already enormous backlog of 136 issues, I'm not so sure anymore.

**Comment by NotMyWing** [comment]
The irony.

Introduced in https://github.com/AE2-UEL/Applied-Energistics-2/commit/0b7341e4a87c469d8d9d3a54d1debaf01b8c2f94.
