### ISSUE TITLE
P2P Tunnel - ME Interface doesn't work with ME Patterns Interface from AE2 UEL: Extended

### ISSUE THREAD

**Issue by skyol1** [AE2-UEL/NAE2#38]
ME Patterns Interface (Interface with more slots for patterns) from [AE2 UEL: Extended](https://www.curseforge.com/minecraft/mc-mods/ae2-uel-extended) cannot push items through the P2P tunnel to the destination.
Versions: NAE2 1.6.1; AE2 UEL: Extended v0.55.30-0.4
The initial problem was that I have many recipes for say twenty identical machines and therefore I have to use more than one ME interface. But it seems that connected ME tunnels cannot take input from more than one ME interface, so I need to attach one new tunnel to the same machine for each new ME interface with new patterns.

**Comment by NotMyWing** [comment]
This is completely on [AE2 UEL: Extended](https://www.curseforge.com/minecraft/mc-mods/ae2-uel-extended). Interface tunnels are expected to work with anything that is an `IInterfaceHost` and has an interface duality. From what I can see, `DualityInterfaceAdv` is implemented as a separate class without any kind of inheritance, thus axing support on their end themselves.

For future reference, NAE2 only supports AE2UEL.
