### ISSUE TITLE
1024k and above fluid cell overflow

### ISSUE THREAD

**Issue by StaffiX** [AE2-UEL/NAE2#39]
AE2UEL version: v0.55.29 
NAE2 version: 1.6.1

after putting more than 2147483 bucket of fluid inside an 1024k (or above), the fluid cell overflows

![javaw_RqNdiRxm5a](https://github.com/AE2-UEL/NAE2/assets/32968022/baf6fc3d-2ac7-44f9-ab7b-41f386b22462)

**Comment by NotMyWing** [comment]
Fixed in AE2:UEL, https://github.com/AE2-UEL/Applied-Energistics-2/commit/f7aa4c92bc72b72909104c5bc870fb70f2bf8d15.
