### ISSUE TITLE
Add Mekanism Support to replace AEAdditions

### ISSUE THREAD

**Issue by mczph** [AE2-UEL/NAE2#44]
[AEAdditions](https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork)

Gas Storage Cells/Components/Buses/Interfaces/Terminals

May require [AE2FluidCraft-Rework](https://github.com/AE2-UEL/AE2FluidCraft-Rework) to be compatible with related gas auto-crafting functions (already implemented in AEAdditions)

**Comment by serenibyss** [comment]
This is planned, though will likely be in its own standalone addon just for Mekanism gas support instead of in any existing project
