### ISSUE TITLE
Uneven distribution of P2P ME Interface resources

### ISSUE THREAD

**Issue by TheTzdDark** [AE2-UEL/NAE2#45]
I am using version nae2-1.6.1 
The problem arises with recipes where there is more than 1 type of item at the input. I tested using the example of a bronze ingot, which is created from 3 copper and 1 tin in the Thermalexpansion induction smelter. For the convenience of tracking, you can enable blocking mode in the ME Interface. 

The bottom line is this, I install 4 induction smelters and connect p2p to them. When ordering a recipe, I get the result that 3 copper ingots get into the first foundry, 1 tin ingot gets into the second foundry, which is why the recipe does not start and everything breaks. As a result, I get leftover items in the mechanisms and unfinished auto craft.

**Comment by NotMyWing** [comment]
This is definitely not what should be happening since resources get sent to tunnels in a package that can't be split. I will investigate.

Does this happen with just the Thermal machines in your case?

**Comment by NotMyWing** [comment]
Actually, are you certain you're using ME Interface tunnels and not Item tunnels?

**Comment by TheTzdDark** [comment]
> Actually, are you certain you're using ME Interface tunnels and not Item tunnels?

Yes, I'm sure

**Comment by TheTzdDark** [comment]
> Actually, are you certain you're using ME Interface tunnels and not Item tunnels?

Oh, I'm sorry, apparently when I was comparing p2p with each other, I actually got this error with the tunnel of items.
After checking with the p2p ME Interface, everything began to work normally, I apologize again :(
