### ISSUE TITLE
ME Interface P2P Tunnels

### ISSUE THREAD

**Issue by RuiXuqi** [AE2-UEL/NAE2#49]
It is unreasonable that everything AE2 adds can change the ME P2P Tunnel into ME Interface P2P Tunnel, even the cables can. The only way to change it back is to flash the Tunnel with a memory card which records the ME P2P Tunnel. The change causes so much trouble when I want to place ME P2P Tunnel instead of the Interface P2P Tunnel. It should only happen when the player right clicks on the ME P2P Tunnel with ME Interface on hand.

**Comment by NotMyWing** [comment]
Fixed in #59.
