### ISSUE TITLE
modpack crashing when adding nae2 to it

### ISSUE THREAD

**Issue by MahoXD2** [AE2-UEL/NAE2#58]
I tried adding nae2 to e2e but no matter what it keeps crashing.

**Comment by juzzlez** [comment]
Same issue for Nomifactory dev edition

**Comment by Exaxxion** [comment]
> I tried adding nae2 to e2e but no matter what it keeps crashing.

Unless you've updated your instance of E2E from AE2 rv6-stable-7 to AE2-UEL (latest or fairly recent version) first, NAE2 is expected to not work. Unreleased commits after NAE2 1.6.1 have added version range checking to Forge's dependency annotation to ensure a compatible version is being used with it.

The mod is also dependent on MixinBooter 8.3+ as it leverages mixins to provide functionality.

> Same issue for Nomifactory dev edition

Nomifactory's latest dev snapshot already has NAE2 1.6.1 in it alongside AE2-UEL 0.56.4, and it works fine from extensive personal testing and not hearing anyone else report such problems in Discord or issue tickets.

**Comment by NotMyWing** [comment]
Please verify that you're using AE2-UEL and not AE2 in your E2E instance. If it still keeps crashing, feel free to attach a log and reopen the issue!
