### ISSUE TITLE
[Suggestion] Interface Terminal compatibility improvements for Interface P2P

### ISSUE THREAD

**Issue by Exaxxion** [AE2-UEL/NAE2#63]
By default, interfaces that have not been renamed display "P2P Tunnel - ME Interface" in the interface terminal as their connected device when exclusively adjacent to an Interface P2P. This makes it difficult to determine what a given interface is actually pushing into, unless you rename every such interface to override the display name.

This has other side effects like Molecular Assemblers not showing up with the Interface Terminal's "Show Crafting interfaces with free slots" button when connected via Interface P2P.

It would be useful if the tunnel could indicate what it's attached to on the other end.

**Comment by NotMyWing** [comment]
Added in 58239b2.
