### ISSUE TITLE
[BUG] P2P Interfaces.

### ISSUE THREAD

**Issue by Artiks54** [AE2-UEL/NAE2#66]
INTERFACE BUG

I have discovered a critical error in the operation of P2P interfaces.

If you connect the p2p interface to the usual interface on the east side, then the p2p interface will transfer to the mechanism as many items per tick as are installed in blocks (coprocessor).

If the p2p interface is connected from any other side, then it will transfer only 1 item per tick, regardless of how many Co-processor blocks there are

![2](https://github.com/AE2-UEL/NAE2/assets/145267469/19eb9b29-8043-4cf7-ab4a-4d9a78ac3d0c)
![64](https://github.com/AE2-UEL/NAE2/assets/145267469/5ce1917d-f472-475c-b999-e82d645730c0)

In addition, sometimes an error appears, the output of the content back to ae

 I also have some ideas for a mod:
1)Please add even cooler x128 x256 x512 coprocessors.
2)Add an improved interface that can transfer as many items as there are in the co-processor system in 1 tick. The usual interface in AE2 Always transmits only 1 item per tick.
3)It would be cool to have such an interface as an Assembly Unit in the LazyAE2 mod

**Comment by NotMyWing** [comment]
Resolved in https://github.com/AE2-UEL/Applied-Energistics-2/issues/440.

You also mentioned there's an error that appears sometimes. If it's still relevant, please open a new issue and attach a log so I can investigate. Thanks!
