### ISSUE TITLE
Job Auto-Complete Card is not supporting Dual Interface

### ISSUE THREAD

**Issue by szukar** [AE2-UEL/NAE2#69]
As in title: we cannot use this card to automatically complete crafts in Dual Interface from AE2 Fluid Crafting Rework. I don't know if this should be threated as bug or feature request, however ME Interface p2p are working correctly (with exception of blocking mode https://github.com/AE2-UEL/NAE2/issues/54).
![card](https://github.com/AE2-UEL/NAE2/assets/57475220/a9efae84-d3fb-43a8-bbbb-4dae5199f8f9)
It cannot be even placed in Dual Interface.

**Comment by Zorbatron** [comment]
Should be resolved with #71
